name: EC2

on:
  workflow_call:

jobs:
  ec2:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v7.0.0
      with:
    # Artifact name
        name: artefato_go
    - uses: actions/checkout@v3
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_USER }}
        EXCLUDE: "postgres-data"
    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: | 
          export DB_HOST=${{ secrets.DB_HOST }}
          export DB_USER=${{ secrets.DB_USER }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export DB_NAME=${{ secrets.DB_NAME }}
          export DB_PORT=${{ secrets.DB_PORT }}
          chmod +x main
          nohup ./main &


          
