name: ECS

on:
  workflow_call:

jobs:
  ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo arquivo da tarefa
        run: aws ecs describe-task-definition --task-definition task_api-go --query taskDefinition > task-definition.json
